/*
 * Copyright 2017 - 2018 Vorlonsoft LLC
 *
 * Licensed under The MIT License (MIT)
 */

// top level gradle config, put dependencies in build.gradle of module
plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.kotlin.android apply false
}

ext {
    appVersionCode = 60

    androidMinSdk = 26
    androidCompileSdk = 36

    javaCompatibility = JavaVersion.VERSION_11
}

allprojects {
    group GROUP
    version VERSION_NAME
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}