// top level gradle config, put dependencies in build.gradle of module

plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
}

ext {
    appVersionCode = 60
    appVersionName = '1.3.0'

    androidMinSdk = 26
    androidCompileSdk = 37

    javaCompatibility = JavaVersion.VERSION_11
}