org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Maven publication
# Ref: https://github.com/vanniktech/gradle-maven-publish-plugin
GROUP=com.stashcat
POM_ARTIFACT_ID=android-rate
VERSION_NAME=3.0.0

POM_NAME=AndroidRate
POM_DESCRIPTION=The AndroidRate library allows you to track statistics about your users' basic app usage. This includes things like the number of app launches and minimum time interval since the installation date.
POM_URL=https://github.com/stashcat-GmbH/AndroidRate/

POM_LICENSE_NAME=MIT
POM_LICENSE_URL=https://opensource.org/license/mit
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/stashcat-GmbH/AndroidRate/
POM_SCM_CONNECTION=scm:git:https://github.com/stashcat-GmbH/AndroidRate.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/stashcat-GmbH/AndroidRate.git

POM_DEVELOPER_ID=stashcat
POM_DEVELOPER_NAME=stashcat GmbH
POM_DEVELOPER_URL=https://stashcat.com/