plugins {
    alias libs.plugins.android.application
    alias libs.plugins.compose.compiler
}

android {
    compileSdk = rootProject.ext.androidCompileSdk

    defaultConfig {
        applicationId 'com.vorlonsoft.android.rate.sample'
        minSdkVersion rootProject.ext.androidMinSdk
        targetSdkVersion rootProject.ext.androidCompileSdk
        versionCode appVersionCode
        versionName appVersionName
    }

    compileOptions {
        sourceCompatibility rootProject.ext.javaCompatibility
        targetCompatibility rootProject.ext.javaCompatibility
    }

    buildFeatures {
        compose true
    }

    buildTypes {
        debug {
            applicationIdSuffix = '.debug'
        }

        release {
            minifyEnabled = true
            shrinkResources = true

            proguardFiles(
                    getDefaultProguardFile('proguard-android-optimize.txt'),
                    rootProject.file('project-proguard-rules.pro'),
                    'proguard-rules.pro'
            )
        }
    }
    namespace 'com.vorlonsoft.android.rate.sample'
}

dependencies {
    implementation project(':library')
    implementation platform(libs.compose.bom)
    implementation libs.bundles.sample.implementation

    debugImplementation libs.bundles.sample.debug
}